openapi: 3.0.0 
info:
  title: API Unit
  version: 1.0.0
  description: Endpoints para integração com a API da UNIT

tags:
  - name: Operações
  - name: Consulta de Dívidas

paths:
  /dinheirow/emiteOperacao:
    post:
      tags:
        - Operações
      summary: Emite operação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_data:
                  type: object
                  properties:
                    cpf: { type: string }
                    email: { type: string, format: email }
                    phone: { type: string }
                    name: { type: string }
                    gender: { type: string }
                    political_exposition: { type: string }
                    city: { type: string }
                    state: { type: string }
                    number_home: { type: string }
                    street: { type: string }
                    complement: { type: string }
                    cep: { type: string }
                    bairro: { type: string }
                    birth_date: { type: string, format: date }
                    mother_name: { type: string }
                    nationality: { type: string }
                    marital_status: { type: string }
                    document_type: { type: string }
                    document_date: { type: string, format: date }
                    document_number: { type: string }
                financial_info:
                  type: object
                  properties:
                    interest_type: { type: string }
                    first_due_date: { type: string, format: date }
                    disbursement_date: { type: string, format: date }
                    fine_configuration:
                      type: object
                      properties:
                        monthly_rate: { type: number, format: float }
                        interest_base: { type: string }
                        contract_fine_rate: { type: number, format: float }
                    credit_operation_type: { type: string }
                    interest_grace_period: { type: integer }
                    monthly_interest_rate: { type: number, format: float }
                    installment_face_value: { type: number, format: float }
                    type_operation: { type: string }
                    limit_days_to_disburse: { type: integer }
                    number_of_installments: { type: integer }
                    principal_grace_period: { type: integer }
                    purchaser_document_number: { type: string }
                    employer_document_number: { type: string }
                    registration_number: { type: string }
                    collateral_type: { type: string }
                disbursement_bank_accounts:
                  type: object
                  properties:
                    typePix: { type: string }
                    name: { type: string }
                    bank_code: { type: string }
                    account_digit: { type: string }
                    branch_number: { type: string }
                    account_number: { type: string }
                    document_number: { type: string }
                    transfer_method: { type: string }
                    percentage_receivable: { type: integer }
                    pixKey: { type: string }
      responses:
        '200':
          description: Operação criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Operação criada com sucesso
        '400':
          description: Erro de validação ou dados inválidos
        '500':
          description: Erro interno no servidor

  /debt:
    get:
      tags:
        - Consulta de Dívidas
      summary: Consulta de dívida por CPF
      description: |
        Consulta as informações de dívida vinculadas a um CPF específico.
        O CPF deve ser enviado como parâmetro de consulta na URL.

        Exemplo:
        GET /debt?cpf=12345678900
      parameters:
        - name: cpf
          in: query
          required: true
          schema:
            type: string
            example: "12345678900"
          description: CPF do titular a ser consultado (somente números).
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    required:
                      - due_installments
                      - due_to_pay
                      - issue_total_amount
                      - num_contracts
                      - total_installments
                    properties:
                      due_installments:
                        type: integer
                        example: 12
                        description: Quantidade de parcelas atualmente em aberto.
                      due_to_pay:
                        type: number
                        format: float
                        example: 1231.93
                        description: Valor total ainda a pagar (somente parcelas em aberto).
                      issue_total_amount:
                        type: number
                        format: float
                        example: 1231.93
                        description: Valor total do débito apurado na consulta.
                      num_contracts:
                        type: integer
                        example: 1
                        description: Quantidade de contratos relacionados ao CPF.
                      total_installments:
                        type: integer
                        example: 12
                        description: Total de parcelas do(s) contrato(s) consultado(s).
                  - type: object
                    properties:
                      mensagem:
                        type: string
                        example: "Não foram encontrados contratos para esse CPF"
                        description: Retorno quando o CPF não possui contratos ou é inválido.
        '400':
          description: CPF inválido ou formato incorreto
        '500':
          description: Erro interno no servidor
