openapi: 3.0.0
info:
  title: API Unit
  version: 1.0.0
  description: Endpoints para integração com a API da UNIT

tags:
  - name: Operações
  - name: Consulta de Dívidas

paths:
  /dinheirow/emiteOperacao:
    post:
      tags:
        - Operações
      summary: Emite operação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_data:
                  type: object
                  properties:
                    cpf: { type: string }
                    email: { type: string, format: email }
                    phone: { type: string }
                    name: { type: string }
                    gender: { type: string }
                    political_exposition: { type: string }
                    city: { type: string }
                    state: { type: string }
                    number_home: { type: string }
                    street: { type: string }
                    complement: { type: string }
                    cep: { type: string }
                    bairro: { type: string }
                    birth_date: { type: string, format: date }
                    mother_name: { type: string }
                    nationality: { type: string }
                    marital_status: { type: string }
                    document_type: { type: string }
                    document_date: { type: string, format: date }
                    document_number: { type: string }
                financial_info:
                  type: object
                  properties:
                    interest_type: { type: string }
                    first_due_date: { type: string, format: date }
                    di
